graphql:
  server:
    mapping: /graphql
    corsEnabled: true
    suppressSpringResponseCodes: true
    query-key: query
    variables-key: variables
    uploadMaxFileSize: 128KB
    uploadMaxRequestSize: 128KB
  schema:
    clientMutationIdName: clientMutationId
    injectClientMutationId: true
    allowEmptyClientMutationId: false
    mutationInputArgumentName: input
    outputObjectNamePrefix: Payload
    inputObjectNamePrefix: Input
    schemaMutationObjectName: Mutation

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: jdbc:mysql://localhost:3307/farm
spring.datasource.username: root
spring.datasource.password:

